### Get the NY Taxi dataset & Specify the types

In [1]:
import pandas as pd

# Read a sample of the data
prefix = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/'
url = f'{prefix}/yellow_tripdata_2021-01.csv.gz'
df = pd.read_csv(url)

/var/folders/qs/rgxk6m0s7b97dgf24mq_wpkc0000gn/T/ipykernel_60851/436693158.py:6: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(url)

In [3]:
# Display first rows
display(df.head())

# Check data types
print(df.dtypes)

# Check data shape
print(df.shape)

# Only the last expression in a cell is automatically displayed, need to use print()/ display() for each calls

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1.0,2021-01-01 00:30:10,2021-01-01 00:36:12,1.0,2.10,1.0,N,142,43,2.0,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1.0,2021-01-01 00:51:20,2021-01-01 00:52:19,1.0,0.20,1.0,N,238,151,2.0,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1.0,2021-01-01 00:43:30,2021-01-01 01:11:06,1.0,14.70,1.0,N,132,165,1.0,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.60,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2.0,2021-01-01 00:31:49,2021-01-01 00:48:21,1.0,4.94,1.0,N,68,33,1.0,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

VendorID                 float64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type             float64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
dtype: object
(1369765, 18)

In [5]:
# dtype = object here, indicating mixed or ambiguous types in df
df.dtypes.iloc[6]

dtype('O')

In [30]:
# Specify dtypes explicitly to avoid pandas chunk-based inference causing mixed-type warnings and unstable schemas
dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "Int64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64"
}

parse_dates = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

#parse_dates tells pandas which columns should be parsed as datetime during CSV loading
df = pd.read_csv(
    url,
    dtype=dtype,
    nrows=100,
    parse_dates=parse_dates
)

In [29]:
df.dtypes.iloc[1]

dtype('<M8[ns]')

### Ingesting Data into Postgres

In [ ]:
#run postgres container and initialize database
'''
!docker run -it --rm
#Using -e to set environment variables
  -e POSTGRES_USER="root"
  -e POSTGRES_PASSWORD="root"
  -e POSTGRES_DB="ny_taxi"
  -v ny_taxi_postgres_data:/var/lib/postgresql
#Creates a named volume, won't be removed after container stops
  -p 5432:5432
  postgres:18
'''

In [ ]:
'''
#Using pgcli to connect to the database，allow to manage database manually in terminal
!uv run pgcli -h localhost -p 5432 -u root -d ny_taxi
'''

In [15]:
# SQLAlchemy provides a high-level Python interface for building SQL queries and managing connections, but it does not talk to the database directly
# psycopg2-binary is the PostgreSQL driver that SQLAlchemy uses underneath to actually connect to the database and execute SQL
'!uv add sqlalchemy psycopg2-binary'

Resolved 120 packages in 15ms
Audited 11 packages in 4ms

In [33]:
#Create engine, using sqlalchemy to connect to postgres db
from sqlalchemy import create_engine
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [24]:
#Check the SQL DDL schema for the database, not doing anything
print(pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine))
#pd.io.sql is a sub module in pandas, get_schema(frame, name, con) returns the SQL DDL schema for the given DataFrame, con=engine: set the syntax by different SQL db

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [26]:
#Init the db and create an empty table with the same schema of the df
'''df.head(0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')'''

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge]
Index: []

In [31]:
#Insert data iteratively into the table
df_iter = pd.read_csv(
    url,
    dtype=dtype,
    parse_dates=parse_dates,
    iterator=True,
    #Not a regular dataframe here, a TextFileReader iterator gets 100,000 rows at a time
    chunksize=100000
)

In [32]:
'''
for df_chunk in df_iter:
    df_chunk.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
    print(len(df_chunk))
'''

100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
100000
69765

In [ ]:
# The integrated version, with using tqdm to show the progress bar
from tqdm.auto import tqdm
first = True

for df_chunk in tqdm(df_iter):

    if first:
        # Create a table with schema (no data)
        df_chunk.head(0).to_sql(
            name="yellow_taxi_data",
            con=engine,
            if_exists="replace"
        )
        first = False
        print("Table created")

    # Insert chunk
    df_chunk.to_sql(
        name="yellow_taxi_data",
        con=engine,
        if_exists="append"
    )

    print("Inserted:", len(df_chunk))

In [ ]:
#Convert the notebook to .py script
'!uv run jupyter nbconvert --to=script ny_taxi.ipynb'